### ISSUE TITLE
編譯問題

### ISSUE THREAD

**Issue by yttina** [HesaiTechnology/HesaiLidarSDK#10]
sudo apt install cmake libproj-dev libpcap-dev libboost-all-dev libyaml-cpp-dev libjpeg-dev libgdal-dev libpq-dev libvtk6-dev libvtk6-qt-dev libpcl-dev 

error:
E: Unable to locate package libvtk6-qt-dev
E: Unable to locate package libpcl-dev

**Comment by trickyMan** [comment]
What's the OS version?
We tested it on Ubuntu 16.04.

**Comment by ghost** [comment]
ubuntu 14.04，使用ubuntu 18.04可以了。
