### ISSUE TITLE
how to install prerequisite on Ubuntu 14.04

### ISSUE THREAD

**Issue by MirrorLakr** [HesaiTechnology/HesaiLidarSDK#4]
kino@Lenovo-G480:~$ sudo apt install cmake libproj-dev libpcap-dev libboost-all-dev libyaml-cpp-dev libjpeg-dev libgdal-dev libpq-dev libvtk6-dev libvtk6-qt-dev libpcl-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libvtk6-qt-dev
E: Unable to locate package libpcl-dev

How can I solve this problem?

**Comment by trickyMan** [comment]
![image](https://user-images.githubusercontent.com/3348813/41389532-f2afff68-6fc3-11e8-9ac3-ee6d5044a4af.png)
I use Ubuntu 16.04 , What is the version of your OS?

**Comment by trickyMan** [comment]
You can search libvtk use `apt search libvtk`

**Comment by MirrorLakr** [comment]
Sorting... Done
Full Text Search... Done
libvtk-java/trusty,now 5.8.0-14.1ubuntu3 amd64 [installed]
  Visualization Toolkit - A high level 3D visualization library - java

libvtk5-dev/trusty,now 5.8.0-14.1ubuntu3 amd64 [installed,automatic]
  VTK header files for building C++ code

libvtk5-qt4-dev/trusty,now 5.8.0-14.1ubuntu3 amd64 [installed]
  Visualization Toolkit - A high level 3D visualization library - Qt devel

libvtk5.8/trusty,now 5.8.0-14.1ubuntu3 amd64 [installed,automatic]
  Visualization Toolkit - A high level 3D visualization library - runtime

libvtk5.8-qt4/trusty,now 5.8.0-14.1ubuntu3 amd64 [installed,automatic]
  Visualization Toolkit - A high level 3D visualization library - Qt runtime

libvtk6/trusty 6.0.0-6 amd64
  Visualization Toolkit - A high level 3D visualization library - runtime

libvtk6-dev/trusty 6.0.0-6 amd64
  VTK header files for building C++ code

libvtk6-java/trusty 6.0.0-6 amd64
  Visualization Toolkit - A high level 3D visualization library - java

libvtkedge/trusty 0.2.0~20110819-2 amd64
  Library of advanced visualization and data processing techniques - runtime

libvtkedge-dev/trusty 0.2.0~20110819-2 amd64
  Library of advanced visualization and data processing techniques - development

libvtkgdcm-cil/trusty 2.2.4-1.1ubuntu4 amd64
  Grassroots DICOM VTK CLI bindings

libvtkgdcm-java/trusty 2.2.4-1.1ubuntu4 amd64
  Grassroots DICOM VTK Java bindings

libvtkgdcm-tools/trusty 2.2.4-1.1ubuntu4 amd64
  Grassroots DICOM VTK tools and utilities

libvtkgdcm2-dev/trusty 2.2.4-1.1ubuntu4 amd64
  Grassroots DICOM VTK development libraries and headers

libvtkgdcm2.2/trusty 2.2.4-1.1ubuntu4 amd64
  Grassroots DICOM VTK runtime libraries

This is the result. And What I need to do next?
