### ISSUE TITLE
关于在Ubuntu中qt开发的一些问题

### ISSUE THREAD

**Issue by chunhuaqiushi1989** [HesaiTechnology/HesaiLidarSDK#6]
你好，禾赛的大牛
我是在QT上开发的，看到你们的开发工程写的比较工整，请问从main进入调用哪个构造函数，以及构造函数的具体参数形式，有没有比较详细的说明，我是想直接从激光雷达获取最原始的点云数据，便于我们处理

**Comment by trickyMan** [comment]
sdk 是一个库，没有main函数入口。用法参照：https://github.com/HesaiTechnology/HesaiLidarSDK/tree/master/sample
