### ISSUE TITLE
本地播放问题

### ISSUE THREAD

**Issue by heathen557** [HesaiTechnology/HesaiLidarSDK#8]
您好！在读取本地录制好的pcap文件时，获取的帧速率很快，没有按照采集的速率播放，请问哪里可以控制下？

**Comment by trickyMan** [comment]
https://github.com/HesaiTechnology/HesaiLidarSDK/blob/master/include/hesaiLidarSDK_IN.h#L55 
你可以改一下这个值，每个包间隔多少us
