### ISSUE TITLE
实时雷达数据接收问题

### ISSUE THREAD

**Issue by heathen557** [HesaiTechnology/HesaiLidarSDK#9]
你好！用 (https://github.com/HesaiTechnology/HesaiLidarSDK/tree/master/sample)下的例子测试，播放本地文件正常，但是链接雷达时，出现问题，SDK打印信息为：“packet size mismatch dual,1262,1256",之后程序会异常退出。
ps:pandar40和pandar40p都试过了，出现了相同问题

**Comment by natsume7** [comment]
用此sdk开发过程中，实时连接激光雷达采集数据出现上述问题，如何解决

**Comment by trickyMan** [comment]
你需要用这个SDK: https://github.com/HesaiTechnology/Pandar40P

**Comment by yttina** [comment]
你好，请问这个SDK有Windows版本的么？

**Comment by trickyMan** [comment]
@yttina 没有Windows版本哈。

**Comment by yttina** [comment]
请问激光数据中时间是根据什么算的呀？
![image](https://user-images.githubusercontent.com/42273673/58164354-84d4d980-7c3a-11e9-8e00-74c592cae3f9.png)
感觉上面代码的逻辑和下面文档的不太一致：
![image](https://user-images.githubusercontent.com/42273673/58164459-be0d4980-7c3a-11e9-81af-44809675b2ee.png)

**Comment by trickyMan** [comment]
哪里不一致呢？

**Comment by yttina** [comment]
代码中段与段之间以及线线之间时间关系如下：
![image](https://user-images.githubusercontent.com/42273673/58468321-3455f400-80f2-11e9-8e86-2edc584f4262.png)

![image](https://user-images.githubusercontent.com/42273673/58468065-b09c0780-80f1-11e9-8199-9aedc5a892bf.png)
文档说明的如下：
![image](https://user-images.githubusercontent.com/42273673/58468368-46379700-80f2-11e9-9bb0-cb3232c95fe2.png)

**Comment by trickyMan** [comment]
So,你的疑问是什么？

**Comment by yttina** [comment]
> So,你的疑问是什么？

以单次回波中第1个block中的第1个laser的时间为例，
t:一包数据的时间,t1:第1个block中的第1个laser的时间
文档逻辑计算时间
t1 = t - (55.56*9 - 0.93*4-1.6*5)/1000000

代码计算时间：
t1 = t - (55.1*5 + 45.18 + 0.93*16 +1.6*15)/1000000

以上，我理解的是否有问题，还请指正，谢谢！

**Comment by trickyMan** [comment]
45.18 是tail的时间，所以需要减去。
packet的timestamp是打包那一刻的时间，你需要反向减去。而文档描述是正向加偏移。
